### ISSUE TITLE
I want you for my army!

### ISSUE THREAD

**Issue by williampietro** [anlsergio/go_crud#1]
Eae Anderson
Gostei do que vi por aqui, tenho um desafio que talvez lhe interesse...

Trabalho em uma gestora de investimentos com o objetivo de desenvolver uma plataforma de crédito pra empresas orientado a dados (AI-First & Cloud Native)
Trabalhamos concedendo empréstimos pra empresas que se cadastram na nossa plataforma e as que são clientes de nossos parceiros. 
Entre nossos parceiros estão: grandes startups de delivery, startups de emissão de nota fiscal e bureaus de crédito.
Nossa faixa salarial atual é acima de 9k reais ;)
O que me diz?

**Comment by anlsergio** [comment]
Fala @williampietro , tudo joia?

Olha, estou bastante satisfeito na Wiley por ora e além disso estou envolvido em alguns projetos bem bacanas e relevantes para a empresa que estão me ajudando a me desenvolver muito, então eu gostaria de terminá-los primeiro antes de poder aceitar outros desafios.

Mas se tiver algum compilado de detalhes maiores sobre a oportunidade (como por ex. a posição, regime de contratação, beneficios, stack de tecnologias, etc) eu gostaria de analisar com carinho.

Inclusive, já te achei no LinkedIn e estou enviando um pedido de conexão para que possamos manter contato, seja em relação a essa, futuras oportunidades ou mesmo pelo simples fato de aumentar meu networking :)

De qualquer forma, já me sinto bastante feliz que voce tenha me considerado para o desafio e que tenha gostado do meu perfil.

Forte abraço!
